### ISSUE TITLE
Eliminate AD tables

### ISSUE THREAD

**Issue by JJ** [salem23/EVOSTAR_2018_GA_FUZZY#10]
We have to take it down to 16 pages, and anyway AD is the worst of all. Just comment the results, taking off 3 tables would fit the paper in 16 pages.

**Comment by amorag** [comment]
AD is the previous controller and I think it is important to show its performance in the comparison. 
To improve it by means of EAs is the aim of the paper, indeed.

I'll manage to fit the contents to 16 pages. ;)

**Comment by JJ** [comment]
2017-11-13 13:46 GMT+01:00 Antonio Mora <notifications@github.com>:

> AD is the previous controller and I think it is important to show its
> performance in the comparison.
> To improve it by means of EAs is the aim of the paper, indeed.
>

I'm not saying its performance shouldn't be mentioned. Keep the
performance, eliminate the tables.

> I'll manage to fit the contents to 16 pages. ;)
>
... and what I have mentioned is the best way to do it. The tables include
spurious information on how good _the other_ controllers have been. That's
irrelevant to the paper.
