### ISSUE TITLE
Bib file missing in Evo2018

### ISSUE THREAD

**Issue by JJ** [salem23/EVOSTAR_2018_GA_FUZZY#17]
~~~
Database file #1: fuzzy_torcs.bib
Warning--I didn't find a database entry for "torcs_Onieva2011"
~~~

**Comment by fergunet** [comment]
Forgot to close it with commit f2046417c5d5ff347fac3fda9994daf6e21282c1 

(I removed that duplicated reference in IPMU paper and forgot to check Evo one)
