### ISSUE TITLE
Improve images

### ISSUE THREAD

**Issue by amorag** [salem23/EVOSTAR_2018_GA_FUZZY#7]
Please Pablo, have a look at the images and improve those you think could be better. ;D

**Comment by fergunet** [comment]
Hi guys. Figure 1 (the flowchart) had a white block below "Steering". I've removed it, but in case it is necessary, please let me know to add it again (with its proper name).

**Comment by amorag** [comment]
Hi, I guess this is to show there are some other things to control by the driving agent, but not considered by the fuzzy controllers. ;)

You can put instead some '...' or so, in order to indicate there could be more modules. :)

Isn't it @salem23?

**Comment by salem23** [comment]
yes it is for the other  actions of the controller
but it looks better now thanks to @fergunet

**Comment by amorag** [comment]
Closed in 2c4efbb7c4ebea076c38dc30c7b4137e1470aa1b
