### ISSUE TITLE
Comment the obtained MFs

### ISSUE THREAD

**Issue by amorag** [salem23/EVOSTAR_2018_GA_FUZZY#9]
Mohammed, please, comment something interesting or curious about the obtained Membership Functions after evolution. 
You can compare them with the initial ones (those of the initial Fuzzy Controller).  ;)

**Comment by JJ** [comment]
:+1:

**Comment by salem23** [comment]
Done

**Comment by amorag** [comment]
Closed in 9fa2d35c66b51f3b33120d074c1f19139f5ecaa8
